#!/bin/bash

URL="https://aviationweather.gov/api/data/metar?ids=KMCI&format=json&taf=false&hours=12&bbox=40%2C-90%2C45%2C-85"
data=$(curl -s "$URL")

receiptTime=$(echo "$data" | jq -r '.[0:6] | .[].receiptTime')

echo "$receiptTime"

