#!/Library/Frameworks/Python.framework/Versions/3.12/bin/python3

import json
import csv


file_one="data/schacon.repos.json"
file_append="chacon.csv"

with open(file_one, 'r') as file:
    data = json.load(file)
with open(file_append, "w", newline="") as csvfile:
    csvwriter = csv.writer(csvfile)
    
    for item in data[:5]:
        
        name = item.get("name", "N/A")
        html_url = item.get("html_url", "N/A")
        updated_at = item.get("updated_at", "N/A")
        visibility = item.get("visibility", "N/A")

        
        csvwriter.writerow([name, html_url, updated_at, visibility])

print(f"Data successfully written to {file_append}")
